### ISSUE TITLE
.gitignore for vim swap files?

### ISSUE THREAD

**Issue by vyp** [romainl/the-patient-vimmer#2]
I see there's a vim swap file: https://github.com/romainl/the-patient-vimmer/blob/gh-pages/.vimrc.swp. I haven't read everything written so far, so I don't know if the swap file is actually a part of the project, but I would imagine not, so I thought I'd bring this up now.

I'm not sure if you already have a preferred regex for ignoring vim temporary files (I had a quick look, but only found [this](https://github.com/romainl/dotvim/blob/0653aa9fc9f368270cd51f59811bd8cb3e6f41c6/.gitignore) instance of a .gitignore) but I think the general consensus is something simple like:

```
*~
*.swp
*.swo
```

But there's also many more differing opinions: http://stackoverflow.com/questions/4824188/git-ignore-vim-temporary-files. iirc `:h recover` has more on this. Github also has some suggested syntax: https://github.com/github/gitignore/blob/master/Global/Vim.gitignore.

I haven't made this a pr because I don't know what pattern(s) you would like, or in case you might not want this at all of course.

**Comment by romainl** [comment]
I noticed that swap file too and planned to get rid of it ASAP.

It's done as of https://github.com/romainl/the-patient-vimmer/commit/c594474447d27704be760327357a2fcedaa1cbfc and I've added a `.gitignore`.

Thank you.
