### ISSUE TITLE
nmap examples may have commands in wrong order 

### ISSUE THREAD

**Issue by fedemp** [romainl/the-patient-vimmer#4]
```
:nmap b B        " change 'b' to work like 'B'
:nmap <F5> dB    " '<F5>' works like 'BD', not like 'dB'
```

Shouldn't it be `db` works as `dB`?

```
:nnoremap <F5> dB    " '<F5>' works like 'bD'
```

Shouldn't it be `db` works as `db`?

**Comment by romainl** [comment]
Hmm… what was I thinking?

Fixed in https://github.com/romainl/the-patient-vimmer/commit/1ca0bab5faf3612bb4ea574bb712f21133638c3a

Thank you!
